### ISSUE TITLE
Create our own addons

### ISSUE THREAD

**Issue by mohitbhatia1994** [Chefkeks/osTicket-Addons#2]
Hey @Chefkeks 

I am really interested in creating my own addons to customize the OSticket otherwise we do customizing by editing the original source code of Osticket which block us to make an easy update to OsTicket. Could you please guide me a little on how I can create my own add-on. 

Thank you
-Mohit

**Comment by Chefkeks** [comment]
Hi Mohit,

what exactly do you plan as an add on?
Basically you can do anything you like with the necessary skills by editing the database directly. Just note that it's risky and we make a nightly backup before we run/execute our add on to sync ldap attributes to the osTicket MySQL database.

Cheers
Michael

**Comment by mohitbhatia1994** [comment]
I don't want to change anything in my database but I want to change my dashboard UI like I want to include a calender instead of graphs. So can I build addons for that ?

**Comment by Chefkeks** [comment]
I guess you'll need to alter the source code for what you're want since I don't think it is possible without modifying the source code. Our approach is different since we just wanted to write information into the database which does not require to modify the database structure or the source files. 

Regarding any bigger changes we either wait for the developers to implement these into osTicket and for us there is no feature missing, so we're not in the need to modify osTicket.
