### ISSUE TITLE
Using LDAP to login without importing users

### ISSUE THREAD

**Issue by faroukmokrani** [Chefkeks/osTicket-Addons#3]
Hi thanks for your Addon ,
so i have integrated the addon succefuly i can see the exist list agents and users but, for the new users
I want to use your addon  for login **directly** without import users ,so if user post a ticket it just login with LDAP and after can post any ticket is it possible ?
there is no need to create any user account anymore ?

Thanks.
Farouk.

**Comment by Chefkeks** [comment]
Hi, Farouk, sorry for the late reply, I must have missed the notification about your issue here.

My addon isn't for creating users, just to sync/update data, but you could do the automatic creation of user accounts via SSO (single sign on). 

Just take a look at the following issue ;)
https://github.com/Chefkeks/osTicket-Addons/issues/5

Regards
Michael
