### ISSUE TITLE
Feature request: import users from LDAP

### ISSUE THREAD

**Issue by timmerk** [Chefkeks/osTicket-Addons#5]
This module appears to only update existing user information, but not create new users from LDAP. Would be a great option. Thanks!

**Comment by Chefkeks** [comment]
You can create users via the official ldap plugin automatically when you combine it with the official http with plugin. Let me know if that is an option for you and I shall provide more info ;)

Since we use the above mentioned single sign on via the 2 official plugins, this addon here is really just to update info from existing users.

Besides, I'm a system administrator with limited time and knowledge, so not really a developer, and due to that limitation I can tell you that any major improvements like adding the creation of users won't happen in the future.

I'm sorry since I guess it's not what you hoped to hear, but I prefer to be honest and don't let people hope for something that won't happen.

Michael

**Comment by timmerk** [comment]
Thanks! That would be perfect if you could let me know how to set it up. I had the official LDAP plugin working with Active Directory (but not LDAP), and the authentication against AD worked perfectly, but I couldn't get it to populate users.

What is the "official http with plugin"? Instructions would be much appreciated.. thanks!

**Comment by Chefkeks** [comment]
I meant the http auth plugin - stupid autocorrect :/ (and yes, answering from a phone :D)

I wrote about single sign on in the osTicket forum. You should have a look at the following discussions (see my next comment).

**Comment by Chefkeks** [comment]
http://osticket.com/forum/discussion/79083/http-passthru

http://osticket.com/forum/discussion/85191/sso-implementation

**Comment by timmerk** [comment]
Thanks! I ran into some problems with the official LDAP plugin and user search, but I will post those issues on the osticket issues page. Thanks.
